/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package michat;


import com.placeholder.PlaceHolder;
import com.sun.deploy.uitoolkit.impl.fx.ui.FXUIFactory;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.xml.ws.Holder;

/**
 *
 * @author ION Xtreme
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
 
    
    Negocio miNegocio;
    int cont=0;
    int img =0;
    
    public Chat() {
        initComponents();
        miNegocio=new Negocio(this);
        txtMensajeEnviar.setCaretPosition(txtMensajeEnviar.getDocument().getLength());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmdEnviar = new javax.swing.JButton();
        cmdVoz = new javax.swing.JToggleButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdAceptar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMensajeEnviar = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JEditorPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sala de Chat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(173, 13, 140, 21);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 46, 70, 15);

        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(80, 40, 227, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mensaje: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 80, 15);

        cmdEnviar.setText("Enviar");
        cmdEnviar.setEnabled(false);
        cmdEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdEnviar);
        cmdEnviar.setBounds(80, 250, 100, 30);

        cmdVoz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/negro.png"))); // NOI18N
        cmdVoz.setEnabled(false);
        cmdVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVozActionPerformed(evt);
            }
        });
        getContentPane().add(cmdVoz);
        cmdVoz.setBounds(200, 250, 40, 33);

        cmdLimpiar.setText("Limpiar chat");
        cmdLimpiar.setEnabled(false);
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLimpiar);
        cmdLimpiar.setBounds(530, 400, 110, 30);

        cmdAceptar.setText("Aceptar");
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAceptar);
        cmdAceptar.setBounds(80, 80, 100, 30);

        txtMensajeEnviar.setEditable(false);
        txtMensajeEnviar.setColumns(20);
        txtMensajeEnviar.setLineWrap(true);
        txtMensajeEnviar.setRows(5);
        txtMensajeEnviar.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtMensajeEnviar);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(80, 130, 230, 110);

        txtMensajes.setEditable(false);
        txtMensajes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtMensajes.setContentType("text/html"); // NOI18N
        txtMensajes.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body background=\"C:\\Users\\ION Xtreme\\Pictures\\001\\argos-1-638.jpg\">\r\n    <p style=\"margin-top: 0\">\r\n      \r\n    </p>\r\n  </body>\r\n</html>\r\n");
        txtMensajes.setToolTipText("");
        txtMensajes.setAutoscrolls(false);
        txtMensajes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtMensajes);
        txtMensajes.getAccessibleContext().setAccessibleParent(txtMensajes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 40, 310, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esta_1.jpg"))); // NOI18N
        jLabel4.setText("asdasdsad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 450);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 270, 2, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarActionPerformed
      if (!this.txtMensajeEnviar.getText().isEmpty()){
          try {
              this.miNegocio.insertarMensaje(this.txtMensajeEnviar.getText());
          } catch (SQLException ex) {
              Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
          }
         
          this.txtMensajeEnviar.setText("");
          this.cmdLimpiar.setEnabled(true);
      }
    }//GEN-LAST:event_cmdEnviarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAceptarActionPerformed
      
        if (!this.txtUsuario.getText().isEmpty()){
            if(!this.txtUsuario.getText().equalsIgnoreCase("Cambiar de Usuario")){
           if (cont==0){
            this.miNegocio.start();
           cont=1;
           }
            this.miNegocio.DefinirUsuario(this.txtUsuario.getText());
            this.txtMensajeEnviar.setEditable(true);
            this.cmdEnviar.setEnabled(true);
            this.txtMensajeEnviar.setEditable(true);
            this.cmdVoz.setEnabled(true);
            this.txtUsuario.setText("");
          PlaceHolder holder = new PlaceHolder(this.txtUsuario, "Cambiar de Usuario");
          this.miNegocio.limpiar();
        }
        }
    }//GEN-LAST:event_cmdAceptarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        if (!this.txtMensajes.getText().isEmpty()){
            this.txtMensajes.setText("");
            this.miNegocio.limpiar();
        }
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if (!this.txtUsuario.getText().isEmpty()){
            this.cmdAceptar.setText("Aceptar");
            this.cmdAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void cmdVozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVozActionPerformed
         if(img==0){
        this.cmdVoz.setIcon(new ImageIcon("src/Imagenes/verde.png"));
           miNegocio.activarVoz(this);
        img=1;
        }else {
            this.cmdVoz.setIcon(new ImageIcon("src/Imagenes/negro.png"));
            miNegocio.cerraVoz();
        img=0;
        }
    }//GEN-LAST:event_cmdVozActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdEnviar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JToggleButton cmdVoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea txtMensajeEnviar;
    public javax.swing.JEditorPane txtMensajes;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
